### ISSUE TITLE
why I have more A items than B

### ISSUE THREAD

**Issue by Rembardino** [viessmann/abc_analysis#3]
I saw also that the example, there are more Aitems than B-items...this does not make sense...or am I wrong?

**Comment by ghlt** [comment]
The division into 3 groups A, B and C is based on certain characteristics of the curve. It may happen that A and B have the same number of items, but this would be the exception rather than the rule. In use cases such as dividing your own customers into A (low revenue), B (medium revenue) and C (high revenue), you can expect the number in A to be much higher than in B.
